@startwbs
* D:/Development/lisp/Dropbox/orgs/GTD/todo_today.org
** ~помидоры~ _
*** Комунлка сделать счета _
*** програимрование точилка
*** Вадим продажи
**** [[*Торговля Вадим][Торговля Вадим]] _
*** Вечерняя йога
*** Телеграм _
**: +------------------~done~------------------+

;
***:DONE Разобрать тудушки _
CLOSED: [2022-05-01 Вс 01:59]
;
****:DONE перекинуть что пороботе в рабочую
CLOSED: [2022-04-25 Пн 17:28]
;
****:DONE раставить приорететы не рабочих
CLOSED: [2022-04-25 Пн 17:28]
;
****:DONE понять нужо ли выделить отельно Игры
CLOSED: [2022-04-21 Чт 22:33]
;
****:DONE Повторить модель из мана орга _
CLOSED: [2022-04-25 Пн 17:29]
;
***** список дел в нот тудее
***** лист действивй здесь
** ~Неважное и несрочное~ _
*** [[file:todo_nottoday.org::*читать Ленд оф лисп][читать Ленд оф лисп]] _
*** [[*начать програмиить рогалик][начать програмиить рогалик]]
*** медитировать _
**:~важное не срочное~

;
** ~Неважное но срочное~
*** [[*ознакомится с сегустивностью][ознакомится с сегустивностью]]
**:~in progress~ _

;
**:~важное срочное~

;
** ~todo~
*** помыть балкон _
*** повесить маскитную сетку _
*** вставить маскитку у сони _
*** [[file:todo_nottoday.org::*зайти в венус хоризонт][зайти в венус хоризонт]] _
*** перекинуть идеи заработка из маны в кагданибуть _
*** сменить мелодию на соню
*** настроить кб для быстрого поиска в новом окне _
**** вики
**** настроить открывать сылку по кнопке в ФФ  _
*** настроить вайфа ТПлинк как асеспоинт\репитер
*** Настроить/скинуть сонин андроид _
**** зарядить
**** попробывть скинуть
*** настроить копирование настроек в дроп бокс
**** фар
**** кют броузер
**** bash
**** папка бин _
**** освоить копирование с архиварованием _
*** Привести в порядок расписание ОРГ агенды _
**** добавить в него про конфиренцию
*****:сайт
Donate
My ticket
Devs For
Ukraine
APRIL 25 & 26, 2022 - 4 PM UTC - LIVESTREAM

